sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install requests
  - pip install -i https://pypi.doubanio.com/simple pytest
  - pip install -i https://pypi.doubanio.com/simple pytest-cov

script:
  - pytest -v
  - pytest --cov=./wulaisdk

#notifications:
#    webhooks: https://oapi.dingtalk.com/robot/send?access_token=096ed387df243a6d60835aadeccc47165f3813bc7cb81cdd0cfeadfd28e3acc1
#    email: false
#    on_success: change
#    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $COV_TOKEN
